ALTER TABLE index_runs ADD COLUMN files_added INTEGER NOT NULL DEFAULT 0;
ALTER TABLE index_runs ADD COLUMN files_modified INTEGER NOT NULL DEFAULT 0;
ALTER TABLE index_runs ADD COLUMN files_deleted INTEGER NOT NULL DEFAULT 0;
